apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      # imagePullSecrets:     #Only required for external container registries, aks has attached acr
      # - name: <secret-name>
      containers:
      - name: server
        image: $ACR_REPO:$IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  type: LoadBalancer
  selector:
    app: $APP_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
